name: azkar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  convex_bottom_bar: ^3.2.0
  adhan: ^2.0.0
  hijri: ^3.0.0
  http: ^1.2.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
 

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - images/
    - fonts/
    - API/
    

  fonts:
    - family: arab
      fonts:
        - asset: fonts/alfont_com.ttf




